const colors = Object.freeze({
    Green: { color: "Green", bgColor: "#164b35", hoverBgColor: "#216e4e" },
    Brown: { color: "Brown", bgColor: "#533f04", hoverBgColor: "#7f5f01" },
    OrangeBrown: { color: "Orange Brown", bgColor: "#702e00", hoverBgColor: "#a54800" },
    RedBrown: { color: "Red Brown", bgColor: "#5d1f1a", hoverBgColor: "#ae2e24" },
    Indigo: { color: "Indigo", bgColor: "#352c63", hoverBgColor: "#5e4db2" },
    MediumGreen: { color: "Medium Green", bgColor: "#216e4e", hoverBgColor: "#164b35" },
    MediumBrown: { color: "Medium Brown", bgColor: "#7f5f01", hoverBgColor: "#533f04" },
    MediumOrangeBrown: { color: "Medium Orange Brown", bgColor: "#a54800", hoverBgColor: "#702e00" },
    MediumRedBrown: { color: "Medium Red Brown", bgColor: "#ae2e24", hoverBgColor: "#5d1f1a" },
    MediumIndigo: { color: "Medium Indigo", bgColor: "#5e4db2", hoverBgColor: "#352c63" },
    Teal: { color: "Teal", bgColor: "#4bce97", hoverBgColor: "#7ee2b8" },
    MustardYellow: { color: "Mustard Yellow", bgColor: "#e2b203", hoverBgColor: "#f5cd47" },
    Peach: { color: "Peach", bgColor: "#fea362", hoverBgColor: "#fec195" },
    Coral: { color: "Coral", bgColor: "#f87168", hoverBgColor: "#fd9891" },
    Lavender: { color: "Lavender", bgColor: "#9f8fef", hoverBgColor: "#b8acf6" },
    NavyBlue: { color: "Navy Blue", bgColor: "#09326c", hoverBgColor: "#0055cc" },
    DarkTeal: { color: "Dark Teal", bgColor: "#164555", hoverBgColor: "#206a83" },
    Olive: { color: "Olive", bgColor: "#37471f", hoverBgColor: "#4c6b1f" },
    DarkMaroon: { color: "Dark Maroon", bgColor: "#50253f", hoverBgColor: "#943d73" },
    SlateGray: { color: "Slate Gray", bgColor: "#454f59", hoverBgColor: "#596773" },
    MediumBlue: { color: "Medium Blue", bgColor: "#0055cc", hoverBgColor: "#09326c" },
    MediumTeal: { color: "Medium Teal", bgColor: "#206a83", hoverBgColor: "#164555" },
    MediumOlive: { color: "Medium Olive", bgColor: "#4c6b1f", hoverBgColor: "#37471f" },
    MediumMaroon: { color: "Medium Maroon", bgColor: "#943d73", hoverBgColor: "#50253f" },
    MediumSlateGray: { color: "Medium Slate Gray", bgColor: "#596773", hoverBgColor: "#454f59" },
    SkyBlue: { color: "Sky Blue", bgColor: "#579dff", hoverBgColor: "#85b8ff" },
    LightBlue: { color: "Light Blue", bgColor: "#6cc3e0", hoverBgColor: "#9dd9ee" },
    LimeGreen: { color: "Lime Green", bgColor: "#94c748", hoverBgColor: "#b3df72" },
    Pink: { color: "Pink", bgColor: "#e774bb", hoverBgColor: "#f797d2" },
    LightSlateGray: { color: "Light Slate Gray", bgColor: "#8c9bab", hoverBgColor: "#9fadbc" },
});

export const colorPairs = Object.entries(colors).map(([colorName, colorDetails]) => ({
    ...colorDetails,
}));
export const defaultLabelColors = [
    colors.Teal,
    colors.MustardYellow,
    colors.MediumRedBrown,
    colors.Coral,
    colors.MediumIndigo,
    colors.MediumBlue,
]